#!/usr/bin/env bash
#
# Creates a DDEV test bench running a real Craft install, for interactive testing that
# unit tests and static analysis cannot cover: the Control Panel backup utility, the
# settings screen, and `craft db/backup` / `craft db/restore` end to end.
#
#   ./dev/scaffold-bench.sh 4
#   ./dev/scaffold-bench.sh 5
#   ./dev/scaffold-bench.sh 6
#
# Benches live outside this repository, because they are shared infrastructure: one
# pair of Craft installs can host every plugin you develop. See ./dev/README.md.
#
# Safe to re-run. It refuses to touch a bench that already exists rather than
# clobbering one you have put work into.

set -euo pipefail

VERSION="${1:-}"
BENCH_ROOT="${CRAFT_BENCH_ROOT:-$HOME/ddev/craft-test-environments}"

# The control panel path. Worth keeping off the default `admin` even locally, so the
# benches exercise the same cpTrigger indirection real sites use, and so nothing in the
# plugin accidentally hardcodes /admin.
CP_TRIGGER="${CRAFT_BENCH_CP_TRIGGER:-webadmin}"
PLUGIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLUGIN_PACKAGE="$(php -r 'echo json_decode(file_get_contents("'"$PLUGIN_DIR"'/composer.json"), true)["name"];')"

# Craft 5 needs PHP 8.2+, Craft 6 needs 8.5+. Craft 4 is pinned to 8.1 here so the
# benches also prove the plugin runs on an older PHP than this machine's default, not
# just a newer one.
#
# INSTALLS_PLUGIN is off for 6: this plugin is built on Yii APIs that Craft 6 replaced
# with Laravel equivalents, so none of the classes it imports exist there.
STABILITY_FLAG=''
INSTALLS_PLUGIN=1
DOCROOT='web'

case "$VERSION" in
    4) CRAFT_CONSTRAINT='^4.3.5'; PHP_VERSION='8.1' ;;
    5) CRAFT_CONSTRAINT='^5.0.0'; PHP_VERSION='8.2' ;;
    6)
        CRAFT_CONSTRAINT='^6.0.0-alpha'
        PHP_VERSION='8.5'
        STABILITY_FLAG='--stability=alpha'
        INSTALLS_PLUGIN=0
        # Craft 6 is a stock Laravel project and serves from public/, not web/. Point
        # DDEV at web/ and every request 404s, because index.php is not there.
        DOCROOT='public'
        ;;
    *) echo "usage: $0 <4|5|6>" >&2; exit 64 ;;
esac

BENCH_DIR="$BENCH_ROOT/v$VERSION"
PROJECT_NAME="craft-bench-v$VERSION"

if [ -d "$BENCH_DIR" ]; then
    echo "Bench already exists at $BENCH_DIR"
    echo "Delete it first if you want a clean one:"
    echo "  cd '$BENCH_DIR' && ddev delete -Oy && cd - && rm -rf '$BENCH_DIR'"
    exit 1
fi

command -v ddev >/dev/null || { echo "ddev is not installed" >&2; exit 1; }
docker info >/dev/null 2>&1 || { echo "Docker is not running" >&2; exit 1; }

# DDEV validates the PHP version before it will start a project, so an old DDEV fails
# here with a message that does not say what to do about it. PHP 8.5 landed in DDEV
# v1.25.0, and Craft 6 requires ^8.5.
if [ "$PHP_VERSION" = '8.5' ]; then
    DDEV_VERSION="$(ddev version -j 2>/dev/null | php -r 'echo json_decode(stream_get_contents(STDIN),true)["raw"]["DDEV version"] ?? "";' | tr -d 'v')"
    OLDEST="$(printf '1.25.0\n%s\n' "$DDEV_VERSION" | sort -V | head -1)"

    if [ -n "$DDEV_VERSION" ] && [ "$OLDEST" != '1.25.0' ]; then
        echo "Craft $VERSION needs PHP $PHP_VERSION, which DDEV only supports from v1.25.0." >&2
        echo "This machine has DDEV v$DDEV_VERSION. Upgrade with:" >&2
        echo "  brew upgrade ddev" >&2
        exit 1
    fi
fi

echo "==> Creating Craft $VERSION bench at $BENCH_DIR (PHP $PHP_VERSION)"
mkdir -p "$BENCH_DIR"
cd "$BENCH_DIR"

ddev config \
    --project-name="$PROJECT_NAME" \
    --project-type=craftcms \
    --docroot="$DOCROOT" \
    --php-version="$PHP_VERSION" \
    --database=mysql:8.0 \
    --auto

# Composer runs inside the web container, so a path repository pointing at a directory
# on the host is meaningless unless that directory is mounted in. Everything under
# the plugins root is mounted to a fixed container path, and the path repository is
# declared against that path rather than a host one.
echo "==> Mounting plugin sources into the container"
cat > .ddev/docker-compose.plugins.yaml <<EOF
# Generated by scaffold-bench.sh. Mounts local plugin repositories into the web
# container so Composer path repositories can resolve them.
#
# To test another plugin, add a line here and run \`ddev restart\`:
#   - "/absolute/path/to/other-plugin:/var/www/plugins/other-plugin"
services:
  web:
    volumes:
      - "$PLUGIN_DIR:/var/www/plugins/$(basename "$PLUGIN_DIR")"
EOF

ddev start

# Ask DDEV rather than assuming <project>.ddev.site, since project-tld is configurable.
SITE_URL="$(ddev describe -j 2>/dev/null | php -r 'echo json_decode(stream_get_contents(STDIN),true)["raw"]["primary_url"] ?? "";')"
SITE_URL="${SITE_URL:-https://$PROJECT_NAME.ddev.site}"

echo "==> Installing Craft $VERSION"
# DDEV 1.25 deprecated `ddev composer create` in favour of `create-project`, and stopped
# consuming a `-y` of its own: anything passed now goes straight through to Composer,
# which has no such flag and aborts. Both spellings are supported here so the script
# works either side of that upgrade.
# shellcheck disable=SC2086 # STABILITY_FLAG is deliberately unquoted; it is often empty
if ddev composer 2>&1 | grep -q 'create-project'; then
    ddev composer create-project --no-scripts $STABILITY_FLAG "craftcms/craft:$CRAFT_CONSTRAINT"
else
    ddev composer create -y --no-scripts $STABILITY_FLAG "craftcms/craft:$CRAFT_CONSTRAINT"
fi

if [ "$VERSION" -ge 6 ]; then
    # Craft 6 is a stock Laravel project: it reads APP_ENV / APP_KEY / DB_* rather than
    # Craft 4 and 5's CRAFT_* variables, and ships only .env.example. Without a .env,
    # APP_ENV is unset, Laravel assumes production, and its guard on destructive
    # commands cancels the installer instead of running it.
    echo "==> Writing .env for the Laravel-style config Craft 6 expects"
    cp .env.example .env

    # APP_URL matters beyond cosmetics: Laravel builds absolute redirects from it, so
    # leaving .env.example's http://localhost sends you off the site after signing in.
    perl -pi -e "
        s|^APP_ENV=.*|APP_ENV=local|;
        s|^APP_DEBUG=.*|APP_DEBUG=true|;
        s|^APP_URL=.*|APP_URL=$SITE_URL|;
        s|^DB_CONNECTION=.*|DB_CONNECTION=mysql|;
        s|^DB_HOST=.*|DB_HOST=db|;
        s|^DB_PORT=.*|DB_PORT=3306|;
        s|^DB_DATABASE=.*|DB_DATABASE=db|;
        s|^DB_USERNAME=.*|DB_USERNAME=db|;
        s|^DB_PASSWORD=.*|DB_PASSWORD=db|;
    " .env

    # The site's baseUrl is stored as a reference to this rather than a literal URL.
    grep -q '^PRIMARY_SITE_URL=' .env || printf '\nPRIMARY_SITE_URL=%s\n' "$SITE_URL" >> .env

    ddev craft key:generate --no-interaction
fi

echo "==> Setting the control panel path to /$CP_TRIGGER"
GENERAL_CONFIG='config/general.php'
[ "$VERSION" -ge 6 ] && GENERAL_CONFIG='config/craft/general.php'

if [ -f "$GENERAL_CONFIG" ] && ! grep -q 'cpTrigger' "$GENERAL_CONFIG"; then
    perl -pi -e "s|^(return GeneralConfig::create\(\))\$|\$1\n    ->cpTrigger('$CP_TRIGGER')|" "$GENERAL_CONFIG"
fi

echo "==> Setting up the site and admin account"
if [ "$VERSION" -ge 6 ]; then
    # Craft 6's console is Symfony's, by way of Laravel: camelCase options, and -n
    # rather than Yii's --interactive=0.
    ddev craft install \
        --username=admin \
        --password=password \
        --email="dev@example.com" \
        --siteName="Craft $VERSION bench" \
        --siteUrl="$SITE_URL" \
        --language=en-US \
        --no-interaction
else
    ddev craft install/craft \
        --username=admin \
        --password=password \
        --email="dev@example.com" \
        --site-name="Craft $VERSION bench" \
        --site-url="\$PRIMARY_SITE_URL" \
        --language=en-US \
        --interactive=0
fi

if [ "$VERSION" -ge 6 ]; then
    # Craft 6 serves its control panel assets through Laravel's Vite integration, which
    # reads a build manifest from public/vendor/craft/build. That is published out of
    # the package by this command, normally from the post-create-project hook that
    # --no-scripts skips above. Without it the CP throws ViteManifestNotFoundException.
    echo "==> Publishing control panel assets"
    ddev craft setup:publish --no-interaction
fi

if [ "$INSTALLS_PLUGIN" -eq 0 ]; then
    echo
    echo "==> Craft $VERSION bench ready (without the plugin)"
    echo "    Directory     : $BENCH_DIR"
    echo
    echo "    $PLUGIN_PACKAGE is not installed here: it targets Craft 4 and 5, which are"
    echo "    built on Yii. Craft 6 replaced that with Laravel, so none of the classes the"
    echo "    plugin imports exist on this bench."
    exit 0
fi

echo "==> Wiring in $PLUGIN_PACKAGE from source"
# The glob picks up every directory mounted above, so adding a plugin later needs a
# mount and a `ddev composer require`, with no change to this repository definition.
ddev composer config repositories.local-plugins '{"type":"path","url":"/var/www/plugins/*","options":{"symlink":true}}'
ddev composer config minimum-stability dev
ddev composer config prefer-stable true
ddev composer require "$PLUGIN_PACKAGE:@dev" -W

# An encryption key has to exist before the plugin will encrypt anything.
if ! grep -q '^SECURE_BACKUPS_KEY=' .env 2>/dev/null; then
    printf '\n# Added by scaffold-bench.sh\nSECURE_BACKUPS_KEY="%s"\n' \
        "$(openssl rand -base64 48 | tr -d '\n')" >> .env
fi

ddev craft plugin/install secure-backups || true

echo
echo "==> Craft $VERSION bench ready"
echo "    Directory     : $BENCH_DIR"
echo "    Control panel : $SITE_URL/$CP_TRIGGER"
echo "    Login         : admin / password"
echo
echo "    Try it:"
echo "      cd '$BENCH_DIR'"
echo "      ddev craft db/backup"
echo "      ddev craft db/restore <path>"
